name: Container

on: push

jobs:
  node-docker:
    runs-on: ubuntu-18.04
    container:
      image: node:17-alpine3.12
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release